namespace ProxyMapService.Proxy.Handlers
{
    public enum HandleStep
    {
        Initialize,
        HttpInitialized,
        HttpAuthenticationNotRequired,
        HttpAuthenticated,
        HttpProxy,
        HttpBypass,
        HttpFile,
        Socks4Initialized,
        Socks4AuthenticationNotRequired,
        Socks4Authenticated,
        Socks4Proxy,
        Socks4Bypass,
        Socks4File,
        Socks5Initialized,
        Socks5AuthenticationNotRequired,
        Socks5UsernamePasswordAuthentication,
        Socks5Authenticated,
        Socks5ConnectRequested,
        Socks5Proxy,
        Socks5Bypass,
        Socks5File,
        Proxy,
        Tunnel,
        Terminate,
    }
}
